CREATE TABLE Cliente(
   CPF INT NOT NULL,
   NOME VARCHAR (50) NOT NULL,
   DATA_NASCIMENTO DATE NOT NULL,
   ENDERECO VARCHAR (50) ,
   SEXO CHAR(1),
   EMAIL VARCHAR(40),
   PRIMARY KEY (CPF)
);

CREATE TABLE Telefone(
  NUMERO INT NOT NULL,
  CPF_CLIENTE INT NOT NULL,
  FOREIGN KEY (CPF_CLIENTE) REFERENCES Cliente(CPF),
  PRIMARY KEY(NUMERO, CPF_CLIENTE)
);

CREATE TABLE Dependente(
   CPF INT NOT NULL,
   NOME VARCHAR (50)     NOT NULL,
   DATA_NASCIMENTO DATE NOT NULL,
   CPF_CLIENTE INT NOT NULL,
   CONSTRAINT PRIMARY KEY (CPF, CPF_CLIENTE),
   CONSTRAINT FOREIGN KEY (CPF_CLIENTE) REFERENCES Cliente(CPF)
);

CREATE TABLE Avaliacao(
   ID INT NOT NULL,
   NOTA  decimal(4,2) NOT NULL,
   DATA DATE NOT NULL,
   CPF_CLIENTE INT NOT NULL,
   COMENTARIO VARCHAR(240),
   PRIMARY KEY (ID),
   FOREIGN KEY (CPF_CLIENTE) REFERENCES Cliente(CPF)
);

CREATE TABLE Quarto(
   NUMERO INT NOT NULL,
   TIPO VARCHAR (20) NOT NULL,
   VISTA VARCHAR (20) NOT NULL,
   VALOR_DIARIA DECIMAL (9, 3),       
   PRIMARY KEY (NUMERO)
);

CREATE TABLE Reserva(
   CPF_CLIENTE INT NOT NULL,
   NUMERO_QUARTO INT NOT NULL,
   DIA_CHECKIN DATE NOT NULL,
   DIA_CHECKOUT DATE NOT NULL,
   FOREIGN KEY (CPF_CLIENTE) REFERENCES Cliente(CPF),
   FOREIGN KEY (NUMERO_QUARTO) REFERENCES Quarto(NUMERO),
   PRIMARY KEY (CPF_CLIENTE, NUMERO_QUARTO)
);

CREATE TABLE Hospeda(
   CPF_CLIENTE INT NOT NULL,
   NUMERO_QUARTO INT NOT NULL,
   DIA_CHECKIN DATE NOT NULL,
   DIA_CHECKOUT DATE NOT NULL,
   FOREIGN KEY (CPF_CLIENTE) REFERENCES Cliente(CPF),
   FOREIGN KEY (NUMERO_QUARTO) REFERENCES Quarto(NUMERO),
   PRIMARY KEY (CPF_CLIENTE, NUMERO_QUARTO)
);

CREATE TABLE Equipamento(
  NUMERO_QUARTO INT NOT NULL,
  NOME VARCHAR(30) NOT NULL,
  FOREIGN KEY (NUMERO_QUARTO) REFERENCES Quarto(NUMERO),
  PRIMARY KEY (NUMERO_QUARTO, NOME)
);

CREATE TABLE Funcionario(
   CPF INT NOT NULL,
   NOME VARCHAR (50)  NOT NULL,
   DATA_NASCIMENTO DATE NOT NULL,
   SALARIO DECIMAL(9,3) NOT NULL,
   FUNCAO VARCHAR(30),
   PRIMARY KEY (CPF)
);

CREATE TABLE Manutencao(
   CPF_FUNCIONARIO INT NOT NULL,
   NUMERO_QUARTO INT NOT NULL,
   DATA DATE NOT NULL,
   TIPO VARCHAR(20) NOT NULL,
   OBSERVACAO VARCHAR(80),
   FOREIGN KEY (CPF_FUNCIONARIO) REFERENCES Cliente(CPF),
   FOREIGN KEY (NUMERO_QUARTO) REFERENCES Quarto(NUMERO),
   PRIMARY KEY (CPF_FUNCIONARIO, NUMERO_QUARTO)
);

CREATE TABLE Produto(
   ID INT NOT NULL,
   NOME VARCHAR (50) NOT NULL,
   VALOR DECIMAL(9,2) NOT NULL,
   DESCRICAO VARCHAR(80),
   TIPO VARCHAR(20) NOT NULL,
   PRIMARY KEY (ID)
);

CREATE TABLE Vendas(
   ID_PRODUTO INT NOT NULL,
   NUMERO_QUARTO INT NOT NULL,
   DATA DATE NOT NULL,
   QUANTIDADE INT NOT NULL,
   FOREIGN KEY (ID_PRODUTO) REFERENCES Produto(ID),
   FOREIGN KEY (NUMERO_QUARTO) REFERENCES Quarto(NUMERO),
   PRIMARY KEY (ID_PRODUTO, NUMERO_QUARTO)
);
